name: pr-validation

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e ."[dev]"
      - name: Test with pytest
        run: |
          pytest
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "E203"
          max-line-length: "89"
          plugins: "flake8-bugbear==22.1.11 flake8-black"